### ISSUE TITLE
關於將屏蔽的頻道改為允許發言的頻道

### ISSUE THREAD

**Issue by longtai-me** [imyimang/discord-gemini-chat-bot#3]
您好，Yimang
我在GitHub看到了您關於Discord API串接Google Gemini API，對此我遇到了一些問題希望您能協助我解決，我的問題是如何修改將Discord Bot限制在特定頻道才能說話，原本是限制在channel.json檔案中含有id的頻道不予理會，但因為我伺服器頻道較多，一個一個設定明顯不確實際，還勞請您給予解答。

**Comment by imyimang** [comment]
> 您好，Yimang 我在GitHub上看到了您關於Discord API串接Google Gemini API，這我遇到了一些問題希望您能幫我解決，我的問題是修改如何將Discord Bot限制在特定頻道才能說話，具體是什麼是限制在channel.json檔案中包含id的頻道不予理會，但因為我的伺服器頻道半徑，一個設定明顯不確實範圍，還勞請您給出解答。


了解,以下是我更改後的程式碼,我自己測試是可以使用的,請您試試看
(可能會有少數註解有些錯誤 因為我並未詳細檢查,但應該可以正常運行)
指令如下:
* openchannel 當前頻道開始接收訊息
* closechannel 取消接收當前頻道的訊息

reset指令和原版一樣
只需要更改main.py即可 Def.py無須更改



[main_py(請解壓縮此檔案).zip](https://github.com/YimangakaLucasTung/discord-gemini-chat-bot/files/13904448/main.zip)

**Comment by longtai-me** [comment]
您好，感謝您的回覆，在收到您的回覆之前，我已透過以下Code解決我遇到的問題：
```py
import discord
from discord.ext import commands
import json

bot = commands.Bot(command_prefix='!', intents=discord.Intents.all())

channel_id = {"id": []}

@bot.event
async def on_ready():
    print(f'{bot.user}')

    for guild in bot.guilds:
        for channel in guild.channels:
            channel_id["id"].append(str(channel.id))

    with open('channel_id.json', 'w') as json_file:
        json.dump(channel, json_file, indent=4)

bot.run('TOKEN')
```

我透過上述Python取得伺服器內所有頻道的ID，並存放於channel.json，啟動後將存放在channel.json刪除允許機器人說話的ID，再次感謝您能夠給予回覆

**Comment by imyimang** [comment]
恭喜你解決問題
不過這種方法需要一個一個伺服器設定,有點麻煩
我修改的檔案是*將channel.json從黑名單更改為白名單功能*
這樣需要使用ai的頻道就能直接打指令來加入白名單,會比較省事

我也有依照你的建議在專案中放了whitelist的版本
如果日後有興趣您可以參考
